import * as THREE from '/three.module.js';

export async function createGame({ui,send}){
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x080b12);scene.fog=new THREE.Fog(0x080b12,14,38);
  const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,60);camera.rotation.order='YXZ';
  const isMobile=matchMedia('(max-width: 850px), (hover: none)').matches;
  const renderer=new THREE.WebGLRenderer({antialias:!isMobile,powerPreference:'high-performance',alpha:false});
  renderer.setPixelRatio(Math.min(devicePixelRatio,isMobile?.85:1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=false;ui.game.innerHTML='';ui.game.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0x7fa8ff,0x111118,1.15));const sun=new THREE.DirectionalLight(0xffffff,.65);sun.position.set(5,10,4);scene.add(sun);

  const TILE=2, MAP=[
    '1111111111111111','1000000000000001','1011011110110101','1001000010000101','1001010010110001','1000010010000001','1011011110101101','1000000000000001','1010110011010101','1000100000010001','1011101111011101','1000001000000001','1001100010110001','1010001000000101','1000000000000001','1111111111111111'];
  const MW=16,MH=16,OX=MW*TILE/2,OZ=MH*TILE/2;
  function world(ix,iz){return{x:(ix+.5)*TILE-OX,z:(iz+.5)*TILE-OZ}}
  function isWall(x,z){const ix=Math.floor((x+OX)/TILE),iz=Math.floor((z+OZ)/TILE);return iz<0||ix<0||iz>=MH||ix>=MW||MAP[iz][ix]==='1'}
  function canStand(x,z,r=.28){return !isWall(x-r,z-r)&&!isWall(x+r,z-r)&&!isWall(x-r,z+r)&&!isWall(x+r,z+r)}
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(MW*TILE,MH*TILE),new THREE.MeshBasicMaterial({color:0x171b22}));floor.rotation.x=-Math.PI/2;scene.add(floor);
  const ceiling=new THREE.Mesh(new THREE.PlaneGeometry(MW*TILE,MH*TILE),new THREE.MeshBasicMaterial({color:0x0c1118,side:THREE.DoubleSide}));ceiling.rotation.x=Math.PI/2;ceiling.position.y=3.2;scene.add(ceiling);
  const wallGeo=new THREE.BoxGeometry(TILE,3.2,TILE),wallMat=new THREE.MeshBasicMaterial({color:0x344051});
  const wallCells=[];for(let z=0;z<MH;z++)for(let x=0;x<MW;x++)if(MAP[z][x]==='1')wallCells.push(world(x,z));
  const walls=new THREE.InstancedMesh(wallGeo,wallMat,wallCells.length),dummy=new THREE.Object3D();
  wallCells.forEach((p,i)=>{dummy.position.set(p.x,1.6,p.z);dummy.updateMatrix();walls.setMatrixAt(i,dummy.matrix)});walls.instanceMatrix.needsUpdate=true;scene.add(walls);
  const neonGeo=new THREE.BoxGeometry(.12,.06,.9),neonBlue=new THREE.MeshBasicMaterial({color:0x176ee8}),neonPurple=new THREE.MeshBasicMaterial({color:0x7a35c8});
  for(let i=0;i<10;i++){const p=world(1+(i*5)%14,1+(i*9)%14);if(!isWall(p.x,p.z)){const lamp=new THREE.Mesh(neonGeo,i%2?neonBlue:neonPurple);lamp.position.set(p.x,3.08,p.z);scene.add(lamp)}}

  function makeHumanoid(color=0xff584f){const g=new THREE.Group(),mat=new THREE.MeshLambertMaterial({color});const dark=new THREE.MeshLambertMaterial({color:0x202631});const head=new THREE.Mesh(new THREE.SphereGeometry(.26,14,10),mat);head.position.y=1.78;g.add(head);const torso=new THREE.Mesh(new THREE.BoxGeometry(.62,.85,.32),mat);torso.position.y=1.18;g.add(torso);for(const sx of [-1,1]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.18,.72,.18),mat);arm.position.set(sx*.43,1.2,-.02);arm.rotation.z=sx*.12;g.add(arm);const leg=new THREE.Mesh(new THREE.BoxGeometry(.22,.72,.24),dark);leg.position.set(sx*.18,.46,0);g.add(leg)}const gun=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,.72),new THREE.MeshLambertMaterial({color:0x253347,emissive:0x08387a,emissiveIntensity:.35}));gun.position.set(.42,1.26,-.42);gun.rotation.x=-.05;g.add(gun);const muzzle=new THREE.PointLight(0x63b8ff,0,3);muzzle.position.set(.42,1.26,-.85);g.add(muzzle);g.userData.muzzle=muzzle;return g}
  const enemy=makeHumanoid();enemy.visible=false;scene.add(enemy);enemy.userData.targetPos=new THREE.Vector3();enemy.userData.targetYaw=0;

  const weaponRoot=new THREE.Group();camera.add(weaponRoot);scene.add(camera);const weaponMeshes=[];
  function makeViewWeapon(color,length,width){const group=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(width,.22,length),new THREE.MeshLambertMaterial({color:0x202832}));body.position.z=-length*.35;group.add(body);const core=new THREE.Mesh(new THREE.BoxGeometry(width*.55,.08,length*.55),new THREE.MeshLambertMaterial({color,emissive:color,emissiveIntensity:1.05}));core.position.set(0,.08,-length*.35);group.add(core);const grip=new THREE.Mesh(new THREE.BoxGeometry(.13,.34,.16),new THREE.MeshLambertMaterial({color:0x11151c}));grip.position.set(0,-.2,-.02);grip.rotation.x=-.25;group.add(grip);const muzzle=new THREE.PointLight(color,0,4);muzzle.position.z=-length*.9;group.add(muzzle);group.userData.muzzle=muzzle;return group}
  const defs={pulse:{name:'PULSE',color:0x58a6ff,clip:12,reserve:60,delay:.28,reload:1050},rapid:{name:'RAPID',color:0x68ffb0,clip:24,reserve:96,delay:.11,reload:1300},scatter:{name:'SCATTER',color:0xffb45c,clip:6,reserve:30,delay:.62,reload:1500}};
  const keysW=Object.keys(defs);for(const k of keysW){const m=makeViewWeapon(defs[k].color,k==='scatter'?1.05:.9,k==='scatter'?.38:.3);m.visible=false;weaponRoot.add(m);weaponMeshes.push(m)}weaponRoot.position.set(.34,-.32,-.55);weaponRoot.rotation.y=.03;

  let mode='none',myId='',room='',hp=100,myScore=0,enemyScore=0,alive=true,yaw=0,pitch=0,weaponKey='pulse',weaponIndex=0,lastShot=0,reloading=false,reloadDone=0,lastSend=0,remote=null,started=false,animId=0,prev=performance.now(),botCd=0,lastFrame=0;
  const ammo={pulse:{clip:12,reserve:60},rapid:{clip:24,reserve:96},scatter:{clip:6,reserve:30}};
  const keys={};let joyX=0,joyY=0,lookId=null,lookX=0,lookY=0,fireHeld=false;

  function updateWeapon(){weaponMeshes.forEach((m,i)=>m.visible=i===weaponIndex);ui.weaponName.textContent=defs[weaponKey].name;const a=ammo[weaponKey];ui.ammo.textContent=a.clip+' / '+a.reserve}
  function updateHUD(){ui.hpFill.style.width=Math.max(0,hp)+'%';ui.score.textContent=myScore+' × '+enemyScore;updateWeapon()}
  function msg(t){ui.netmsg.textContent=t}
  function flashHit(){ui.hit.style.opacity=1;setTimeout(()=>ui.hit.style.opacity=0,90)}
  function damageFlash(){ui.damage.style.opacity=.85;setTimeout(()=>ui.damage.style.opacity=0,120)}
  function tracer(from,to,color){const geo=new THREE.BufferGeometry().setFromPoints([from,to]);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity:.95}));scene.add(line);setTimeout(()=>{scene.remove(line);line.geometry.dispose();line.material.dispose()},85)}
  const sparkGeo=new THREE.SphereGeometry(.022,4,3),sparkMats=new Map();function spark(p,color){let mat=sparkMats.get(color);if(!mat){mat=new THREE.MeshBasicMaterial({color});sparkMats.set(color,mat)}for(let i=0;i<3;i++){const s=new THREE.Mesh(sparkGeo,mat);s.position.copy(p).add(new THREE.Vector3((Math.random()-.5)*.14,(Math.random()-.5)*.14,(Math.random()-.5)*.14));scene.add(s);setTimeout(()=>scene.remove(s),90)}}
  function muzzle(){const m=weaponMeshes[weaponIndex].userData.muzzle;m.intensity=6;weaponRoot.position.z=-.50;setTimeout(()=>{m.intensity=0;weaponRoot.position.z=-.55},60)}
  function switchWeapon(){if(reloading)return;weaponIndex=(weaponIndex+1)%keysW.length;weaponKey=keysW[weaponIndex];if(mode==='online')send({type:'switch',weapon:weaponKey});updateWeapon()}
  function reload(){if(!alive||reloading)return;const d=defs[weaponKey],a=ammo[weaponKey];if(a.clip>=d.clip||a.reserve<=0)return;reloading=true;reloadDone=performance.now()+d.reload;msg('RECARREGANDO...');if(mode==='online')send({type:'reload',weapon:weaponKey});}
  function completeLocalReload(){const d=defs[weaponKey],a=ammo[weaponKey],need=d.clip-a.clip,take=Math.min(need,a.reserve);a.clip+=take;a.reserve-=take;reloading=false;updateHUD();msg(mode==='training'?'TREINO':'VALENDO!')}
  function shoot(){if(!started||!alive||reloading)return;const d=defs[weaponKey],a=ammo[weaponKey],now=performance.now()/1000;if(now-lastShot<d.delay)return;if(a.clip<=0){reload();return}lastShot=now;muzzle();if(mode==='online'){a.clip--;send({type:'shoot',weapon:weaponKey,yaw,pitch});updateHUD();return}a.clip--;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const objs=[];enemy.traverse(o=>{if(o.isMesh)objs.push(o)});const hits=ray.intersectObjects(objs,false);const from=camera.getWorldPosition(new THREE.Vector3());const dir=camera.getWorldDirection(new THREE.Vector3());let to=from.clone().add(dir.multiplyScalar(18));if(hits.length){to=hits[0].point.clone();remote.hp=Math.max(0,remote.hp-(weaponKey==='scatter'?16:weaponKey==='rapid'?6:10));flashHit();spark(to,d.color);if(remote.hp<=0){enemy.visible=false;myScore++;updateHUD();setTimeout(respawnBot,1600)}}tracer(from,to,d.color);updateHUD()}
  function respawnBot(){remote={x:12,z:12,hp:100,alive:true};enemy.position.set(12,0,12);enemy.visible=true}
  function move(dt){if(!alive)return;let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)+joyY,s=(keys.d?1:0)-(keys.a?1:0)+joyX;const len=Math.hypot(f,s);if(len>1){f/=len;s/=len}const speed=4.3,fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw),dx=(fx*f+rx*s)*speed*dt,dz=(fz*f+rz*s)*speed*dt,nx=camera.position.x+dx,nz=camera.position.z+dz;if(canStand(nx,camera.position.z))camera.position.x=nx;if(canStand(camera.position.x,nz))camera.position.z=nz;camera.rotation.y=yaw;camera.rotation.x=pitch;weaponRoot.position.y=-.32+(Math.abs(f)+Math.abs(s)>.1?Math.sin(performance.now()*.012)*.018:0);if(reloading&&performance.now()>=reloadDone&&mode==='training')completeLocalReload();if(fireHeld)shoot()}
  function bot(dt){if(mode!=='training'||!enemy.visible||!alive)return;const dx=camera.position.x-enemy.position.x,dz=camera.position.z-enemy.position.z,dist=Math.hypot(dx,dz),ang=Math.atan2(-dx,-dz);enemy.rotation.y=ang;if(dist>5){const nx=enemy.position.x+dx/dist*.9*dt,nz=enemy.position.z+dz/dist*.9*dt;if(canStand(nx,enemy.position.z))enemy.position.x=nx;if(canStand(enemy.position.x,nz))enemy.position.z=nz}botCd-=dt;if(dist<13&&botCd<=0){botCd=.85+Math.random()*.45;hp=Math.max(0,hp-6);damageFlash();updateHUD();const from=new THREE.Vector3(enemy.position.x,1.35,enemy.position.z),to=camera.position.clone();tracer(from,to,0xff5c65);if(hp<=0){alive=false;ui.dead.classList.add('on');enemyScore++;updateHUD();setTimeout(()=>{camera.position.set(-12,1.62,-12);hp=100;alive=true;ui.dead.classList.remove('on');updateHUD()},1700)}}}
  function smoothEnemy(dt){if(mode!=='online'||!enemy.userData.hasTarget)return;enemy.position.lerp(enemy.userData.targetPos,Math.min(1,dt*12));let d=((enemy.userData.targetYaw-enemy.rotation.y+Math.PI*3)%(Math.PI*2))-Math.PI;enemy.rotation.y+=d*Math.min(1,dt*12)}
  function tick(t){if(!started)return;if(isMobile&&t-lastFrame<22){animId=requestAnimationFrame(tick);return}lastFrame=t;const dt=Math.min(.04,(t-prev)/1000||.022);prev=t;move(dt);bot(dt);smoothEnemy(dt);if(mode==='online'&&t-lastSend>100){lastSend=t;send({type:'move',x:camera.position.x,z:camera.position.z,yaw,pitch,weapon:weaponKey})}renderer.render(scene,camera);animId=requestAnimationFrame(tick)}
  function startCommon(){if(started)return;started=true;prev=performance.now();updateHUD();animId=requestAnimationFrame(tick)}
  function startOnline(j){mode='online';myId=j.id;room=j.room;camera.position.set(j.spawn.x,1.62,j.spawn.z);yaw=j.yaw||0;pitch=0;Object.assign(ammo,j.ammo||{});enemy.visible=false;msg('AGUARDANDO O OUTRO JOGADOR...');startCommon()}
  function startTraining(){mode='training';camera.position.set(-12,1.62,-12);yaw=0;pitch=0;remote={x:12,z:12,hp:100,alive:true};enemy.position.set(12,0,12);enemy.visible=true;msg('TREINO');startCommon()}
  function handleMessage(m){if(m.type==='matchStart'){enemy.visible=true;msg('VALENDO!');return}if(m.type==='snapshot'){const me=m.players.find(p=>p.id===myId),op=m.players.find(p=>p.id!==myId);if(me){hp=me.hp;myScore=me.score;alive=me.alive;if(me.ammo)for(const k of Object.keys(me.ammo))Object.assign(ammo[k],me.ammo[k]);ui.dead.classList.toggle('on',!alive)}if(op){enemyScore=op.score;enemy.visible=op.alive;enemy.userData.targetPos.set(op.x,0,op.z);enemy.userData.targetYaw=op.yaw||0;enemy.userData.hasTarget=true}updateHUD();return}if(m.type==='shot'){const from=new THREE.Vector3(m.from.x,m.from.y,m.from.z),to=new THREE.Vector3(m.to.x,m.to.y,m.to.z);tracer(from,to,defs[m.weapon]?.color||0xffffff);if(m.hit){spark(to,defs[m.weapon]?.color||0xffffff);if(m.shooter===myId)flashHit();if(m.target===myId)damageFlash()}return}if(m.type==='reloaded'&&m.id===myId){if(m.ammo)Object.assign(ammo[m.weapon],m.ammo);reloading=false;updateHUD();msg('VALENDO!');return}if(m.type==='eliminated'){msg(m.killer===myId?'PONTO SEU!':'VOCÊ FOI DERRUBADO');return}if(m.type==='matchEnd'){msg(m.winner===myId?'VOCÊ VENCEU!':'ADVERSÁRIO VENCEU!');return}if(m.type==='peerLeft'){enemy.visible=false;msg('O OUTRO JOGADOR SAIU');return}if(m.type==='error')msg(m.message||'Erro')}
  function onDisconnect(){msg('CONEXÃO ENCERRADA')}

  addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,isMobile?.85:1.25));renderer.setSize(innerWidth,innerHeight)});
  addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space'){e.preventDefault();shoot()}if(e.key.toLowerCase()==='r')reload();if(e.key.toLowerCase()==='q')switchWeapon()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
  renderer.domElement.addEventListener('click',()=>{if(innerWidth>850&&document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock().catch(()=>{})});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0025;pitch-=e.movementY*.0022;pitch=Math.max(-1.05,Math.min(1.05,pitch))}});
  let stickId=null;function stickMove(e){if(e.pointerId!==stickId)return;const r=ui.moveStick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy),max=r.width*.34,s=Math.min(1,max/(l||1)),x=dx*s,y=dy*s;joyX=x/max;joyY=-y/max;ui.moveKnob.style.transform=`translate(${x}px,${y}px)`}ui.moveStick.addEventListener('pointerdown',e=>{stickId=e.pointerId;ui.moveStick.setPointerCapture(e.pointerId);stickMove(e)});ui.moveStick.addEventListener('pointermove',stickMove);function endStick(e){if(e.pointerId!==stickId)return;stickId=null;joyX=joyY=0;ui.moveKnob.style.transform='translate(0,0)'}ui.moveStick.addEventListener('pointerup',endStick);ui.moveStick.addEventListener('pointercancel',endStick);
  ui.look.addEventListener('pointerdown',e=>{lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;ui.look.setPointerCapture(e.pointerId)});ui.look.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;const dx=e.clientX-lookX,dy=e.clientY-lookY;lookX=e.clientX;lookY=e.clientY;yaw-=dx*.0055;pitch-=dy*.0048;pitch=Math.max(-1.05,Math.min(1.05,pitch))});const endLook=e=>{if(e.pointerId===lookId)lookId=null};ui.look.addEventListener('pointerup',endLook);ui.look.addEventListener('pointercancel',endLook);
  ui.fireBtn.addEventListener('pointerdown',e=>{e.preventDefault();fireHeld=true;shoot();ui.fireBtn.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])ui.fireBtn.addEventListener(ev,e=>{e.preventDefault();fireHeld=false});ui.reloadBtn.addEventListener('pointerdown',e=>{e.preventDefault();reload()});ui.switchBtn.addEventListener('pointerdown',e=>{e.preventDefault();switchWeapon()});

  updateWeapon();
  return {startOnline,startTraining,handleMessage,onDisconnect};
}
